
services:
  app:
    image: panel-api-server:latest
    container_name: panel-api-server
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
    volumes:
      - ./channels:/app/channels
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
      - ./mails:/app/mails
      - ./static:/app/staticstatic
      - ./tasks:/app/tasks
      - ./uploadfiles:/app/uploadfiles
      - ./views:/app/views
    ports:
      - 4000:4000

  postgres:
    image: postgres:15-alpine
    container_name: apanel-api-db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    container_name: panel-api-redis
    restart: always
    volumes:
      - ./redis/data:/data
      - ./redis/logs:/logs
    command: redis-server --requirepass ${REDIS_PASS}